server:
  port: 8000

spring:
  sql:
    init:
      mode: always
      data-locations: classpath:db/*.sql
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    database: POSTGRESQL
    properties:
      hibernate:
        hbm2ddl:
          import_files:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_NAME:postgres}
    password: ${POSTGRES_PASSWORD:123}
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
  database:
    driverClassName: org.postgresql.Driver
