server:
  port: 8000

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    database: POSTGRESQL
    properties:
      hibernate:
        hbm2ddl:
          import_files:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_NAME:postgres}
    password: ${POSTGRES_PASSWORD:123}
  database:
    driverClassName: org.postgresql.Driver
